### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by webxoss** [Deardrops/webxoss-deckeditor2#53]
### Milestone 1 - Release DeckEditor

- [ ] ~~Style deck select~~
- [x] #52 Save to / Load from `localStorage`
- [x] #57  Localize
- [x] #66 Mayu's Room

### Milestone 2 - Improve DeckEditor

- [ ] #45 Offline
- [x] #73 #74 Import/Export
- [ ] Load language files dynamically
- [ ] Raw image in gallery
- [ ] FAQ in detail
- [ ] More icons
- [ ] Change log
- [ ] Settings
- [ ] #80 Cache manager
- [ ] Account system

### Milestone 3 - Responsive DeckEditor

- [ ] Design layouts for pad and PC

### Milestone 4 - WEBXOSS NEXT

- [ ] Rebuild the whole WEBXOSS client
